2024-05-29 09:52:59,907:ERROR:Failed to retrieve data
Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000210550D2710>, 'Connection to data.rennesmetropole.fr timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.rennesmetropole.fr', port=443): Max retries exceeded with url: /api/explore/v2.1/catalog/datasets/etat-du-trafic-en-temps-reel/exports/json?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000210550D2710>, 'Connection to data.rennesmetropole.fr timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aarcidiaco\Desktop\rennes_traffic_ko\src\get_data.py", line 12, in __init__
    response = requests.get(self.url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='data.rennesmetropole.fr', port=443): Max retries exceeded with url: /api/explore/v2.1/catalog/datasets/etat-du-trafic-en-temps-reel/exports/json?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000210550D2710>, 'Connection to data.rennesmetropole.fr timed out. (connect timeout=None)'))
2024-05-29 09:55:28,790:INFO:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-05-29 09:55:28,790:INFO:[33mPress CTRL+C to quit[0m
2024-05-29 10:00:32,117:INFO:127.0.0.1 - - [29/May/2024 10:00:32] "GET / HTTP/1.1" 200 -
2024-05-29 10:00:33,064:INFO:127.0.0.1 - - [29/May/2024 10:00:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-05-29 10:00:51,704:INFO:127.0.0.1 - - [29/May/2024 10:00:51] "POST / HTTP/1.1" 200 -
2024-05-29 10:04:26,466:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "[32mGET /dashboard HTTP/1.1[0m" 308 -
2024-05-29 10:04:26,476:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "[32mGET /dashboard/ HTTP/1.1[0m" 302 -
2024-05-29 10:04:26,505:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "GET /dashboard/login HTTP/1.1" 200 -
2024-05-29 10:04:26,795:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "[36mGET /dashboard/static/css/main.css HTTP/1.1[0m" 304 -
2024-05-29 10:04:26,803:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "GET /dashboard/static/img/header.png HTTP/1.1" 200 -
2024-05-29 10:04:26,875:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "[36mGET /dashboard/static/fonts/fa-solid-900.woff2 HTTP/1.1[0m" 304 -
2024-05-29 10:04:26,923:INFO:127.0.0.1 - - [29/May/2024 10:04:26] "[36mGET /dashboard/static/js/app.js HTTP/1.1[0m" 304 -
2024-05-29 10:04:27,102:INFO:127.0.0.1 - - [29/May/2024 10:04:27] "[36mGET /dashboard/static/pages/overview.html HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,062:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[32mPOST /dashboard/login HTTP/1.1[0m" 302 -
2024-05-29 10:04:32,070:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "GET /dashboard/ HTTP/1.1" 200 -
2024-05-29 10:04:32,098:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[36mGET /dashboard/static/css/main.css HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,100:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[36mGET /dashboard/static/js/app.js HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,331:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[36mGET /dashboard/static/pages/overview.html HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,339:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[36mGET /dashboard/static/elements/menu.html HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,349:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[36mGET /dashboard/static/elements/modal.html HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,379:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "GET /dashboard/api/custom_graphs HTTP/1.1" 200 -
2024-05-29 10:04:32,380:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "[36mGET /dashboard/static/pages/telemetry.html HTTP/1.1[0m" 304 -
2024-05-29 10:04:32,453:INFO:127.0.0.1 - - [29/May/2024 10:04:32] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-29 10:04:33,790:ERROR:Exception on /dashboard/api/deploy_details [GET]
Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\core\auth.py", line 39, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\views\deployment.py", line 25, in deploy_details
    datetime.datetime.fromtimestamp(details['first-request'])
OSError: [Errno 22] Invalid argument
2024-05-29 10:04:33,797:INFO:127.0.0.1 - - [29/May/2024 10:04:33] "[35m[1mGET /dashboard/api/deploy_details HTTP/1.1[0m" 500 -
2024-05-29 10:04:34,805:INFO:127.0.0.1 - - [29/May/2024 10:04:34] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-29 10:05:34,329:INFO:127.0.0.1 - - [29/May/2024 10:05:34] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:36,456:INFO:127.0.0.1 - - [29/May/2024 10:05:36] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:38,615:INFO:127.0.0.1 - - [29/May/2024 10:05:38] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:40,515:INFO:127.0.0.1 - - [29/May/2024 10:05:40] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:43,299:INFO:127.0.0.1 - - [29/May/2024 10:05:43] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:47,436:INFO:127.0.0.1 - - [29/May/2024 10:05:47] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:50,027:INFO:127.0.0.1 - - [29/May/2024 10:05:50] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:52,661:INFO:127.0.0.1 - - [29/May/2024 10:05:52] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:55,816:INFO:127.0.0.1 - - [29/May/2024 10:05:55] "POST / HTTP/1.1" 200 -
2024-05-29 10:05:58,209:INFO:127.0.0.1 - - [29/May/2024 10:05:58] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:00,716:INFO:127.0.0.1 - - [29/May/2024 10:06:00] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:04,132:INFO:127.0.0.1 - - [29/May/2024 10:06:04] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:07,288:INFO:127.0.0.1 - - [29/May/2024 10:06:07] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:10,971:INFO:127.0.0.1 - - [29/May/2024 10:06:10] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:13,725:INFO:127.0.0.1 - - [29/May/2024 10:06:13] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:16,479:INFO:127.0.0.1 - - [29/May/2024 10:06:16] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:19,247:INFO:127.0.0.1 - - [29/May/2024 10:06:19] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:22,094:INFO:127.0.0.1 - - [29/May/2024 10:06:22] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:25,026:INFO:127.0.0.1 - - [29/May/2024 10:06:25] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:28,167:INFO:127.0.0.1 - - [29/May/2024 10:06:28] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:31,974:INFO:127.0.0.1 - - [29/May/2024 10:06:31] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:36,318:INFO:127.0.0.1 - - [29/May/2024 10:06:36] "POST / HTTP/1.1" 200 -
2024-05-29 10:06:41,681:INFO:127.0.0.1 - - [29/May/2024 10:06:41] "POST / HTTP/1.1" 200 -
2024-05-29 11:50:51,229:INFO:127.0.0.1 - - [29/May/2024 11:50:51] "POST / HTTP/1.1" 200 -
2024-05-29 11:52:54,518:INFO:127.0.0.1 - - [29/May/2024 11:52:54] "POST / HTTP/1.1" 200 -
2024-05-29 12:08:32,491:INFO:127.0.0.1 - - [29/May/2024 12:08:32] "POST / HTTP/1.1" 200 -
2024-05-29 12:08:33,688:INFO:127.0.0.1 - - [29/May/2024 12:08:33] "POST / HTTP/1.1" 200 -
2024-05-29 12:08:37,249:INFO:127.0.0.1 - - [29/May/2024 12:08:37] "POST / HTTP/1.1" 200 -
2024-05-29 12:08:41,659:INFO:127.0.0.1 - - [29/May/2024 12:08:41] "POST / HTTP/1.1" 200 -
2024-05-29 12:08:46,925:INFO:127.0.0.1 - - [29/May/2024 12:08:46] "POST / HTTP/1.1" 200 -
2024-05-29 13:38:13,825:INFO:127.0.0.1 - - [29/May/2024 13:38:13] "POST / HTTP/1.1" 200 -
2024-05-29 13:38:31,985:INFO:127.0.0.1 - - [29/May/2024 13:38:31] "POST / HTTP/1.1" 200 -
2024-05-29 14:16:32,031:INFO:127.0.0.1 - - [29/May/2024 14:16:32] "POST / HTTP/1.1" 200 -
2024-05-29 14:16:44,780:INFO:127.0.0.1 - - [29/May/2024 14:16:44] "POST / HTTP/1.1" 200 -
2024-05-29 14:46:45,996:INFO:127.0.0.1 - - [29/May/2024 14:46:45] "GET /dashboard/overview HTTP/1.1" 200 -
2024-05-29 14:46:46,061:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/css/main.css HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,153:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/fonts/fa-solid-900.woff2 HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,160:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/js/app.js HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,576:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/elements/menu.html HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,581:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/elements/modal.html HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,591:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/pages/overview.html HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,681:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "[36mGET /dashboard/static/pages/telemetry.html HTTP/1.1[0m" 304 -
2024-05-29 14:46:46,780:INFO:127.0.0.1 - - [29/May/2024 14:46:46] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-29 14:46:47,724:INFO:127.0.0.1 - - [29/May/2024 14:46:47] "GET /dashboard/api/custom_graphs HTTP/1.1" 200 -
2024-05-29 14:46:47,737:INFO:127.0.0.1 - - [29/May/2024 14:46:47] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-29 14:46:47,800:ERROR:Exception on /dashboard/api/deploy_details [GET]
Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\core\auth.py", line 39, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\views\deployment.py", line 25, in deploy_details
    datetime.datetime.fromtimestamp(details['first-request'])
OSError: [Errno 22] Invalid argument
2024-05-29 14:46:47,813:INFO:127.0.0.1 - - [29/May/2024 14:46:47] "[35m[1mGET /dashboard/api/deploy_details HTTP/1.1[0m" 500 -
2024-05-29 14:46:51,889:INFO:127.0.0.1 - - [29/May/2024 14:46:51] "POST / HTTP/1.1" 200 -
2024-05-29 14:46:55,925:INFO:127.0.0.1 - - [29/May/2024 14:46:55] "POST / HTTP/1.1" 200 -
2024-05-29 15:18:06,913:INFO:127.0.0.1 - - [29/May/2024 15:18:06] "POST / HTTP/1.1" 200 -
2024-05-29 15:18:17,199:INFO:127.0.0.1 - - [29/May/2024 15:18:17] "POST / HTTP/1.1" 200 -
2024-05-29 15:18:21,486:INFO:127.0.0.1 - - [29/May/2024 15:18:21] "POST / HTTP/1.1" 200 -
2024-05-30 09:30:42,312:ERROR:Failed to retrieve data
Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025FB2E12E50>, 'Connection to data.rennesmetropole.fr timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.rennesmetropole.fr', port=443): Max retries exceeded with url: /api/explore/v2.1/catalog/datasets/etat-du-trafic-en-temps-reel/exports/json?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025FB2E12E50>, 'Connection to data.rennesmetropole.fr timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aarcidiaco\Desktop\rennes_traffic_ko\src\get_data.py", line 12, in __init__
    response = requests.get(self.url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='data.rennesmetropole.fr', port=443): Max retries exceeded with url: /api/explore/v2.1/catalog/datasets/etat-du-trafic-en-temps-reel/exports/json?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025FB2E12E50>, 'Connection to data.rennesmetropole.fr timed out. (connect timeout=None)'))
2024-05-30 09:32:19,634:INFO:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-05-30 09:32:19,634:INFO:[33mPress CTRL+C to quit[0m
2024-05-30 09:32:47,674:INFO:127.0.0.1 - - [30/May/2024 09:32:47] "GET / HTTP/1.1" 200 -
2024-05-30 09:32:47,937:INFO:127.0.0.1 - - [30/May/2024 09:32:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-05-30 09:32:52,092:INFO:127.0.0.1 - - [30/May/2024 09:32:52] "POST / HTTP/1.1" 200 -
2024-05-30 09:32:56,420:INFO:127.0.0.1 - - [30/May/2024 09:32:56] "POST / HTTP/1.1" 200 -
2024-05-30 09:33:01,844:INFO:127.0.0.1 - - [30/May/2024 09:33:01] "POST / HTTP/1.1" 200 -
2024-05-30 09:33:03,633:INFO:127.0.0.1 - - [30/May/2024 09:33:03] "POST / HTTP/1.1" 200 -
2024-05-30 10:13:30,227:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "[32mGET /dashboard HTTP/1.1[0m" 308 -
2024-05-30 10:13:30,253:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "[32mGET /dashboard/ HTTP/1.1[0m" 302 -
2024-05-30 10:13:30,332:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "GET /dashboard/login HTTP/1.1" 200 -
2024-05-30 10:13:30,490:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "[36mGET /dashboard/static/css/main.css HTTP/1.1[0m" 304 -
2024-05-30 10:13:30,491:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "GET /dashboard/static/img/header.png HTTP/1.1" 200 -
2024-05-30 10:13:30,547:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "[36mGET /dashboard/static/fonts/fa-solid-900.woff2 HTTP/1.1[0m" 304 -
2024-05-30 10:13:30,582:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "[36mGET /dashboard/static/js/app.js HTTP/1.1[0m" 304 -
2024-05-30 10:13:30,864:INFO:127.0.0.1 - - [30/May/2024 10:13:30] "[36mGET /dashboard/static/pages/overview.html HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,137:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[32mPOST /dashboard/login HTTP/1.1[0m" 302 -
2024-05-30 10:13:35,145:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "GET /dashboard/ HTTP/1.1" 200 -
2024-05-30 10:13:35,167:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[36mGET /dashboard/static/css/main.css HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,170:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[36mGET /dashboard/static/js/app.js HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,326:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[36mGET /dashboard/static/pages/overview.html HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,336:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[36mGET /dashboard/static/elements/modal.html HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,337:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[36mGET /dashboard/static/elements/menu.html HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,366:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "GET /dashboard/api/custom_graphs HTTP/1.1" 200 -
2024-05-30 10:13:35,370:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "[36mGET /dashboard/static/pages/telemetry.html HTTP/1.1[0m" 304 -
2024-05-30 10:13:35,427:INFO:127.0.0.1 - - [30/May/2024 10:13:35] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 10:13:36,876:ERROR:Exception on /dashboard/api/deploy_details [GET]
Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\core\auth.py", line 39, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\views\deployment.py", line 25, in deploy_details
    datetime.datetime.fromtimestamp(details['first-request'])
OSError: [Errno 22] Invalid argument
2024-05-30 10:13:36,894:INFO:127.0.0.1 - - [30/May/2024 10:13:36] "[35m[1mGET /dashboard/api/deploy_details HTTP/1.1[0m" 500 -
2024-05-30 10:13:37,909:INFO:127.0.0.1 - - [30/May/2024 10:13:37] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-30 10:18:08,557:INFO:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-05-30 10:18:08,557:INFO:[33mPress CTRL+C to quit[0m
2024-05-30 10:19:32,213:INFO:127.0.0.1 - - [30/May/2024 10:19:32] "POST / HTTP/1.1" 200 -
2024-05-30 10:19:33,311:INFO:127.0.0.1 - - [30/May/2024 10:19:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-05-30 10:19:39,249:INFO:127.0.0.1 - - [30/May/2024 10:19:39] "POST / HTTP/1.1" 200 -
2024-05-30 10:19:42,917:INFO:127.0.0.1 - - [30/May/2024 10:19:42] "GET /dashboard/overview HTTP/1.1" 200 -
2024-05-30 10:19:42,998:INFO:127.0.0.1 - - [30/May/2024 10:19:42] "GET /dashboard/static/css/main.css HTTP/1.1" 200 -
2024-05-30 10:19:43,019:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/static/fonts/fa-solid-900.woff2 HTTP/1.1" 200 -
2024-05-30 10:19:43,082:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/static/js/app.js HTTP/1.1" 200 -
2024-05-30 10:19:43,410:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/static/elements/menu.html HTTP/1.1" 200 -
2024-05-30 10:19:43,410:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/static/elements/modal.html HTTP/1.1" 200 -
2024-05-30 10:19:43,413:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/static/pages/overview.html HTTP/1.1" 200 -
2024-05-30 10:19:43,429:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/api/custom_graphs HTTP/1.1" 200 -
2024-05-30 10:19:43,454:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "[36mGET /dashboard/static/pages/telemetry.html HTTP/1.1[0m" 304 -
2024-05-30 10:19:43,465:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/static/img/favicon.ico HTTP/1.1" 200 -
2024-05-30 10:19:43,478:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 10:19:43,495:ERROR:Exception on /dashboard/api/deploy_details [GET]
Traceback (most recent call last):
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\core\auth.py", line 39, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aarcidiaco\AppData\Local\anaconda3\Lib\site-packages\flask_monitoringdashboard\views\deployment.py", line 25, in deploy_details
    datetime.datetime.fromtimestamp(details['first-request'])
OSError: [Errno 22] Invalid argument
2024-05-30 10:19:43,507:INFO:127.0.0.1 - - [30/May/2024 10:19:43] "[35m[1mGET /dashboard/api/deploy_details HTTP/1.1[0m" 500 -
2024-05-30 10:19:45,771:INFO:127.0.0.1 - - [30/May/2024 10:19:45] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-30 10:19:56,252:INFO:127.0.0.1 - - [30/May/2024 10:19:56] "POST / HTTP/1.1" 200 -
2024-05-30 10:19:56,373:INFO:127.0.0.1 - - [30/May/2024 10:19:56] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-05-30 10:32:46,277:INFO:127.0.0.1 - - [30/May/2024 10:32:46] "POST / HTTP/1.1" 200 -
2024-05-30 10:32:50,390:INFO:127.0.0.1 - - [30/May/2024 10:32:50] "POST / HTTP/1.1" 200 -
2024-05-30 10:32:53,741:INFO:127.0.0.1 - - [30/May/2024 10:32:53] "POST / HTTP/1.1" 200 -
2024-05-30 10:32:58,972:INFO:127.0.0.1 - - [30/May/2024 10:32:58] "POST / HTTP/1.1" 200 -
2024-05-30 10:34:20,713:INFO:127.0.0.1 - - [30/May/2024 10:34:20] "POST / HTTP/1.1" 200 -
2024-05-30 10:34:23,779:INFO:127.0.0.1 - - [30/May/2024 10:34:23] "POST / HTTP/1.1" 200 -
2024-05-30 11:53:29,737:INFO:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-05-30 11:53:29,737:INFO:[33mPress CTRL+C to quit[0m
2024-05-30 11:54:48,580:INFO:127.0.0.1 - - [30/May/2024 11:54:48] "POST / HTTP/1.1" 200 -
2024-05-30 11:54:50,702:INFO:127.0.0.1 - - [30/May/2024 11:54:50] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-05-30 11:54:58,420:INFO:127.0.0.1 - - [30/May/2024 11:54:58] "POST / HTTP/1.1" 200 -
2024-05-30 11:54:58,670:INFO:127.0.0.1 - - [30/May/2024 11:54:58] "[36mGET /dashboard/static/css/main.css HTTP/1.1[0m" 304 -
2024-05-30 11:54:58,786:INFO:127.0.0.1 - - [30/May/2024 11:54:58] "[36mGET /dashboard/static/js/app.js HTTP/1.1[0m" 304 -
2024-05-30 11:54:58,966:INFO:127.0.0.1 - - [30/May/2024 11:54:58] "[36mGET /dashboard/static/fonts/fa-solid-900.woff2 HTTP/1.1[0m" 304 -
2024-05-30 11:54:59,218:INFO:127.0.0.1 - - [30/May/2024 11:54:59] "[36mGET /dashboard/static/elements/menu.html HTTP/1.1[0m" 304 -
2024-05-30 11:54:59,264:INFO:127.0.0.1 - - [30/May/2024 11:54:59] "[36mGET /dashboard/static/elements/modal.html HTTP/1.1[0m" 304 -
2024-05-30 11:54:59,294:INFO:127.0.0.1 - - [30/May/2024 11:54:59] "[36mGET /dashboard/static/pages/overview.html HTTP/1.1[0m" 304 -
2024-05-30 11:54:59,387:INFO:127.0.0.1 - - [30/May/2024 11:54:59] "GET /dashboard/api/custom_graphs HTTP/1.1" 200 -
2024-05-30 11:54:59,776:INFO:127.0.0.1 - - [30/May/2024 11:54:59] "[36mGET /dashboard/static/pages/telemetry.html HTTP/1.1[0m" 304 -
2024-05-30 11:55:00,054:INFO:127.0.0.1 - - [30/May/2024 11:55:00] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 11:55:00,150:INFO:127.0.0.1 - - [30/May/2024 11:55:00] "GET /dashboard/api/deploy_details HTTP/1.1" 200 -
2024-05-30 11:55:02,609:INFO:127.0.0.1 - - [30/May/2024 11:55:02] "GET /dashboard/static/pages/configuration.html HTTP/1.1" 200 -
2024-05-30 11:55:02,798:INFO:127.0.0.1 - - [30/May/2024 11:55:02] "GET /dashboard/api/users HTTP/1.1" 200 -
2024-05-30 11:55:02,970:INFO:127.0.0.1 - - [30/May/2024 11:55:02] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 11:55:04,101:INFO:127.0.0.1 - - [30/May/2024 11:55:04] "GET /dashboard/api/deploy_config HTTP/1.1" 200 -
2024-05-30 11:55:04,618:INFO:127.0.0.1 - - [30/May/2024 11:55:04] "GET /dashboard/api/deploy_details HTTP/1.1" 200 -
2024-05-30 11:55:05,470:INFO:127.0.0.1 - - [30/May/2024 11:55:05] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-30 11:55:14,823:INFO:127.0.0.1 - - [30/May/2024 11:55:14] "GET /dashboard/static/pages/database_management.html HTTP/1.1" 200 -
2024-05-30 11:55:14,835:INFO:127.0.0.1 - - [30/May/2024 11:55:14] "GET /dashboard/database_pruning/get_database_size HTTP/1.1" 200 -
2024-05-30 11:55:14,836:INFO:127.0.0.1 - - [30/May/2024 11:55:14] "[33mGET /dashboard/database_pruning/get_pruning_schedule HTTP/1.1[0m" 404 -
2024-05-30 11:55:22,260:INFO:127.0.0.1 - - [30/May/2024 11:55:22] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 11:55:23,287:INFO:127.0.0.1 - - [30/May/2024 11:55:23] "GET /dashboard/api/deploy_details HTTP/1.1" 200 -
2024-05-30 11:55:23,294:INFO:127.0.0.1 - - [30/May/2024 11:55:23] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-30 11:55:23,309:INFO:127.0.0.1 - - [30/May/2024 11:55:23] "GET /dashboard/static/elements/monitorLevel.html HTTP/1.1" 200 -
2024-05-30 11:55:26,952:INFO:127.0.0.1 - - [30/May/2024 11:55:26] "GET /dashboard/static/pages/plotly_graph.html HTTP/1.1" 200 -
2024-05-30 11:55:26,977:INFO:127.0.0.1 - - [30/May/2024 11:55:26] "GET /dashboard/static/elements/endpointDetails.html HTTP/1.1" 200 -
2024-05-30 11:55:28,000:INFO:127.0.0.1 - - [30/May/2024 11:55:28] "GET /dashboard/api/hourly_load/2024-05-16/2024-05-30/1 HTTP/1.1" 200 -
2024-05-30 11:55:28,001:INFO:127.0.0.1 - - [30/May/2024 11:55:28] "GET /dashboard/api/endpoint_info/1 HTTP/1.1" 200 -
2024-05-30 11:55:37,478:INFO:127.0.0.1 - - [30/May/2024 11:55:37] "POST / HTTP/1.1" 200 -
2024-05-30 11:55:39,901:INFO:127.0.0.1 - - [30/May/2024 11:55:39] "POST / HTTP/1.1" 200 -
2024-05-30 11:55:42,537:INFO:127.0.0.1 - - [30/May/2024 11:55:42] "POST / HTTP/1.1" 200 -
2024-05-30 11:55:45,159:INFO:127.0.0.1 - - [30/May/2024 11:55:45] "POST / HTTP/1.1" 200 -
2024-05-30 11:55:47,940:INFO:127.0.0.1 - - [30/May/2024 11:55:47] "POST / HTTP/1.1" 200 -
2024-05-30 11:55:52,849:INFO:127.0.0.1 - - [30/May/2024 11:55:52] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 11:55:53,866:INFO:127.0.0.1 - - [30/May/2024 11:55:53] "GET /dashboard/api/deploy_details HTTP/1.1" 200 -
2024-05-30 11:55:53,885:INFO:127.0.0.1 - - [30/May/2024 11:55:53] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-30 11:55:58,921:INFO:127.0.0.1 - - [30/May/2024 11:55:58] "GET /dashboard/api/hourly_load/2024-05-16/2024-05-30 HTTP/1.1" 200 -
2024-05-30 11:56:12,682:INFO:127.0.0.1 - - [30/May/2024 11:56:12] "GET /dashboard/api/endpoints_hits HTTP/1.1" 200 -
2024-05-30 11:56:13,698:INFO:127.0.0.1 - - [30/May/2024 11:56:13] "POST /dashboard/api/api_performance HTTP/1.1" 200 -
2024-05-30 11:56:31,537:INFO:127.0.0.1 - - [30/May/2024 11:56:31] "POST /dashboard/api/api_performance HTTP/1.1" 200 -
2024-05-30 11:57:49,793:INFO:127.0.0.1 - - [30/May/2024 11:57:49] "GET /dashboard/static/pages/reporting.html HTTP/1.1" 200 -
2024-05-30 11:57:52,750:INFO:127.0.0.1 - - [30/May/2024 11:57:52] "POST /dashboard/api/reporting/make_report/intervals HTTP/1.1" 200 -
2024-05-30 11:57:58,896:INFO:127.0.0.1 - - [30/May/2024 11:57:58] "GET /dashboard/api/endpoints_hits HTTP/1.1" 200 -
2024-05-30 11:57:59,910:INFO:127.0.0.1 - - [30/May/2024 11:57:59] "POST /dashboard/api/api_performance HTTP/1.1" 200 -
2024-05-30 11:58:01,603:INFO:127.0.0.1 - - [30/May/2024 11:58:01] "GET /dashboard/api/requests/2024-05-20/2024-05-30 HTTP/1.1" 200 -
2024-05-30 11:58:05,779:INFO:127.0.0.1 - - [30/May/2024 11:58:05] "GET /dashboard/api/endpoints_hits HTTP/1.1" 200 -
2024-05-30 11:58:05,780:INFO:127.0.0.1 - - [30/May/2024 11:58:05] "GET /dashboard/api/versions HTTP/1.1" 200 -
2024-05-30 11:58:06,816:INFO:127.0.0.1 - - [30/May/2024 11:58:06] "POST /dashboard/api/multi_version HTTP/1.1" 200 -
2024-05-30 11:58:11,980:INFO:127.0.0.1 - - [30/May/2024 11:58:11] "GET /dashboard/api/hourly_load/2024-05-16/2024-05-30 HTTP/1.1" 200 -
2024-05-30 11:58:41,015:INFO:127.0.0.1 - - [30/May/2024 11:58:41] "GET /dashboard/api/hourly_load/2024-05-20/2024-05-31 HTTP/1.1" 200 -
2024-05-30 11:59:50,097:INFO:127.0.0.1 - - [30/May/2024 11:59:50] "GET /dashboard/telemetry/get_is_telemetry_answered HTTP/1.1" 200 -
2024-05-30 11:59:51,099:INFO:127.0.0.1 - - [30/May/2024 11:59:51] "GET /dashboard/api/overview HTTP/1.1" 200 -
2024-05-30 11:59:51,112:INFO:127.0.0.1 - - [30/May/2024 11:59:51] "GET /dashboard/api/deploy_details HTTP/1.1" 200 -
2024-05-30 14:07:51,102:INFO:127.0.0.1 - - [30/May/2024 14:07:51] "POST / HTTP/1.1" 200 -
2024-05-30 14:07:51,524:INFO:127.0.0.1 - - [30/May/2024 14:07:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-05-30 14:07:56,921:INFO:127.0.0.1 - - [30/May/2024 14:07:56] "GET /dashboard/api/hourly_load/2024-05-16/2024-05-30/1 HTTP/1.1" 200 -
2024-05-30 14:07:56,923:INFO:127.0.0.1 - - [30/May/2024 14:07:56] "GET /dashboard/api/endpoint_info/1 HTTP/1.1" 200 -
